version: '3.6'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    entrypoint: /mssql/entrypoint.sh
    command: /opt/mssql/bin/sqlservr
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql:/mssql
    ports:
      - "15785:1433"
  trino:
    image: "starburstdata/starburst-enterprise:356-e.5"
    ports:
      - "8080:8080"
    volumes:
      - ./starburst/etc:/etc/starburst
    depends_on:
      - mssql
  app:
    image: cohortextractor-dev
    build: 
      context: .
      target: cohortextractor-dev
    volumes:
      - .:/app
    depends_on:
      - mssql
      - trino
